### ISSUE TITLE
Partie 3

### ISSUE THREAD

**Issue by martintsd** [YoucefZemmouri/Unsupervised_Learning_P2#2]
Quelques commentaires :

- Dans le bout de code que le professeur a donné, ligne 16 on charge un fichier .mat et ligne 20 à 24 on récupère ses coordonnées. Cependant, avec la boucle qui est en ligne 2, on ouvre tous les fichiers .mat du dossier et on ré-écrit la variable `X` à chaque fois. J’ai trouvé ça bizarre, c’est pourquoi j’ai stocké le `X` de chaque fichier .mat dans une variable `X_global`.
(La fonction load_data que j’ai codée donne les mêmes résultats que la fonction Matlab de l’énoncé)

- Je n’ai pas bien compris si je devais faire les tests de clustering sur tous les fichiers `.mat` du dossier ou bien sur quelques exemples. Pour l’instant j’ai mis un exemple (le premier `.mat`, à savoir Hopkins155/1R2RC).

- Je ne sais pas très bien comment choisir les paramètres des algorithmes (Pour K-subspaces, je n’ai pas très bien compris sur quel sous-espace on cherche les données, même si dimension 3 semble bien marcher, Pour subspace clustering aucune idée …). Il y a un ReadMe dans le dossier Hopkins155, si vous pouviez jeter un coup d’oeil.

- @flm8620, peut-être on peut factoriser le calcul de l’affinité avec K-NN et le mettre dans Tools (voir ma fonction `affinity`)

**Comment by flm8620** [comment]
* Je pense le code du prof est just pour monter comment charger un ficher

* Je pense un ou deux example suffit, le prof veut voir plutôt les choix de paramètre. 

* Aucune idée sur la dimension du sous-espace de movement des points. Pour Subspace clustering, je trouve difficile à choisir le mu2 et epsilon. Parfois je trouve si on diminuer epsilon pour bien converger, l'erreur de clustring est encore plus grand, bizarre ..

* C'est fait, j'ai aussi ajouter un "show error table" pour P3
